config/routes.rb
Rails.application.routes.draw do

  post 'permission_slip/:session_id' => 'signed_slips#save_slip'
  get 'permission_slip/:session_id' => 'unsigned_slips#get_slip'

  get 'unauthorized' => 'unsigned_slips#unauthorized'
  
  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

def new
  @article = Article.new	 
  authorize! :create, @article, message: "create Article"
end

def index	
  authorize! :read, Article, message: "read Article"	 
  @articles = Article.accessible_by(current_ability)	 
 
end

def create
  @article = Article.new(article_params)
  authorize! :create, @article, message: "create Article"
  if @article.save
    redirect_to @article
  else
    render 'new'
  end
end

def show
  @article = Article.find(params[:id])
  authorize! :read, @article, message: "read Article" 
end

def edit
  @article = Article.find(params[:id])
  authorize! :edit, @article, message: "edit Article"
end

def update
  @article = Article.find(params[:id])
  authorize! :edit, @article, message: "edit Article"
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end

def destroy
  @article = Article.find(params[:id])
  authorize! :destroy, @article, message: "destroy Article"
  @article.destroy 
  redirect_to articles_path
end

private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<% unless @article.nil? %>
  <%= form_for @article do |f| %>
    <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
   
    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>
   
    <p>
      <%= f.submit %>
    </p>
  <% end %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>

<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article_path(article),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
<%= link_to 'Edit Article', edit_article_path(@article) %> |
<%= link_to 'Back to Articles', articles_path %>